import { auth } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { NextResponse } from 'next/server'

function fmt(n: number) {
  return n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

export async function GET(req: Request) {
  const session = await auth()
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  const userId = (session.user as any).id
  const { searchParams } = new URL(req.url)
  const year = parseInt(searchParams.get('year') ?? String(new Date().getFullYear()))

  const employee = await prisma.employee.findUnique({
    where: { userId },
    select: { id: true, employeeNo: true, position: true, taxId: true },
  })
  if (!employee) return NextResponse.json({ error: 'No employee record' }, { status: 404 })

  const payslips = await prisma.payslip.findMany({
    where: {
      employeeId: employee.id,
      payrollPeriod: { year },
    },
    include: { payrollPeriod: true },
    orderBy: { payrollPeriod: { month: 'asc' } },
  })

  const user = await prisma.user.findUnique({ where: { id: userId }, select: { firstName: true, lastName: true, email: true } })
  const tenant = await prisma.tenant.findUnique({ where: { id: (session.user as any).tenantId }, select: { name: true } })

  const totals = payslips.reduce((acc, p) => ({
    gross: acc.gross + p.basicSalary + p.allowances,
    deductions: acc.deductions + p.deductions,
    net: acc.net + p.netPay,
  }), { gross: 0, deductions: 0, net: 0 })

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Tax Certificate ${year}</title>
<style>
body{font-family:Arial,sans-serif;max-width:700px;margin:40px auto;color:#111;font-size:14px}
.header{text-align:center;border-bottom:3px double #4f46e5;padding-bottom:20px;margin-bottom:24px}
h1{font-size:24px;margin:0 0 4px}
.subtitle{color:#6b7280;font-size:13px}
table{width:100%;border-collapse:collapse;margin:12px 0}
th,td{padding:10px 14px;text-align:left;border:1px solid #e5e7eb}
th{background:#f9fafb;font-weight:600;color:#374151}
.total-row{background:#f0fdf4;font-weight:700;color:#166534}
.stamp{text-align:center;margin-top:40px;color:#6b7280;font-size:12px;border-top:1px solid #e5e7eb;padding-top:16px}
</style></head><body>
<div class="header">
  <p class="subtitle">${tenant?.name ?? 'Tera SM'}</p>
  <h1>Annual Tax Certificate</h1>
  <p class="subtitle">Tax Year: 1 January ${year} – 31 December ${year}</p>
</div>
<table>
  <tr><th>Employee Name</th><td>${user?.firstName} ${user?.lastName}</td></tr>
  <tr><th>Employee No</th><td>${employee.employeeNo}</td></tr>
  <tr><th>Position</th><td>${employee.position}</td></tr>
  <tr><th>Tax ID / TIN</th><td>${employee.taxId ?? 'N/A'}</td></tr>
  <tr><th>Email</th><td>${user?.email}</td></tr>
</table>
<h3>Annual Earnings Summary</h3>
<table>
  <tr><th>Month</th><th>Gross</th><th>Deductions</th><th>Net Pay</th></tr>
  ${payslips.map(p => `<tr>
    <td>${p.payrollPeriod.name}</td>
    <td>$${fmt(p.basicSalary + p.allowances)}</td>
    <td>$${fmt(p.deductions)}</td>
    <td>$${fmt(p.netPay)}</td>
  </tr>`).join('')}
  <tr class="total-row">
    <td>TOTAL ${year}</td>
    <td>$${fmt(totals.gross)}</td>
    <td>$${fmt(totals.deductions)}</td>
    <td>$${fmt(totals.net)}</td>
  </tr>
</table>
<div class="stamp">
  <p>This certificate is generated by ${tenant?.name ?? 'Tera SM'} and is valid for tax filing purposes.</p>
  <p>Generated on ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
</div>
</body></html>`

  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `attachment; filename="tax-certificate-${year}.html"`,
    },
  })
}
